"--- vimrc ---"

"- General
set nocompatible

"- File Encode
set encoding=utf-8
set fileencodings=utf-8,euc-jp,cp932

"- Behavior
"-- General behavior
set backspace=indent,eol,start
set nobackup
set writebackup

"-- Editor behavior
set autoindent
set ts=4
set expandtab
set showmatch

"- View
syntax on
set number
set wrap
set laststatus=2
set showcmd 

"- Color
" if !has('gui_running')
"   set t_Co=256
" endif

"- Application
"-- Vindle
filetype off
  set rtp+=~/.vim/vundle.git/
  call vundle#rc()
    Bundle 'itchyny/lightline.vim'
filetype on
