" Plugins 
" - NeoBundle
if has('vim_starting')
    set nocompatible               " Be iMproved
    set runtimepath+=~/.vim/bundle/neobundle.vim/
endif
call neobundle#rc(expand('~/.vim/bundle/'))
NeoBundleFetch 'Shougo/neobundle.vim'

"   bundles here:
NeoBundle 'itchyny/lightline.vim'
NeoBundle 'Shougo/neosnippet.vim'
NeoBundle 'Shougo/neosnippet-snippets'
NeoBundle 'scrooloose/nerdtree'
NeoBundle 'derekwyatt/vim-scala.git'    " Scala syntax coloring

"   finish
filetype plugin indent on

" ---------------------------------------------------------------------------- "

" File Encodings
set encoding=utf-8
set fileencodings=utf-8,euc-jp,cp932

" Behavior
" - vim
set backspace=indent,eol,start
set nobackup
set writebackup
set history=50

" - indent
set smartindent
set tabstop=4
set ts=4
set shiftwidth=4
set expandtab
set autoindent

" - search
set hlsearch

" View
" - general
syntax on
set number
set ruler
set wrap
set showcmd 
set cursorline
set smartcase
set showmatch

" Pulugin Settings
" - NERDTree
nmap <silent> <C-e> :NERDTreeToggle<CR>
vmap <silent> <C-e> <Esc> :NERDTreeToggle<CR>
omap <silent> <C-e> :NERDTreeToggle<CR>
imap <silent> <C-e> <Esc> :NERDTreeToggle<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
let g:NERDTreeShowHidden=1

" - lightline
set laststatus=2
