# Tap dupes and versions
tap homebrew/dupes
tap homebrew/binary
tap homebrew/homebrew-php

# Update homebrew
update

# Common
install nmap
install fcrackzip
install youtube-dl
install lha

# Developer Tool
install zsh
install git
install tig
install nkf
install wget curl
install heroku

install vim --override-system-vi --with-lua --with-python3
install emacs

# Language
install php55

install go
install clisp
install mit-scheme
install lua
install node

# Language provided by xxenv
install rbenv ruby-build
install plenv perl-build

# SDK
install android-sdk

# Applications
install packer
install mysql
install redis
install phpmyadmin
