" prerequirements:
" pip3 install --user pynvim

" PLUGIN: Shougo/dein.vim
if &compatible
  set nocompatible
endif
" Add the dein installation directory into runtimepath
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim

if dein#load_state('~/.cache/dein')
  call dein#begin('~/.cache/dein')

  call dein#add('~/.cache/dein/repos/github.com/Shougo/dein.vim')
  call dein#add('Shougo/deoplete.nvim')

  call dein#add('Shougo/defx.nvim')

  if !has('nvim')
    call dein#add('roxma/nvim-yarp')
    call dein#add('roxma/vim-hug-neovim-rpc')
  endif

  call dein#add('itchyny/lightline.vim')
  call dein#add('Yggdroot/indentLine')
  call dein#add('junegunn/vim-easy-align')
  call dein#add('altercation/vim-colors-solarized')

  call dein#end()
  call dein#save_state()
endif

filetype plugin indent on
syntax enable

" file encodings
set encoding=utf-8
set fileencodings=utf-8,cp932,euc-jp

" general settings
set wrap
set showcmd
set cursorline
set smartcase
set showmatch
set matchtime=1

" view
set number
set ruler
set laststatus=2 "show status line at any time
set colorcolumn=120
highlight ColorColumn ctermbg = 239

" behavior
set backspace=indent,eol,start
set nobackup
set writebackup
set history=50
set hlsearch
autocmd BufWritePre * :%s/\s\+$//e "truncate line-tail space(s)
set autoindent
set smartindent
set expandtab
set tabstop=2
set shiftwidth=2
set ignorecase

augroup filetypedetect
  " override tab size by detecting file type
  au BufNewFile,BufRead *.php setlocal tabstop=4 shiftwidth=4
augroup END

" PLUGIN: Shougo/deoplete
let g:deoplete#enable_at_startup = 1

" PLUGIN: Shougo/defx.nvim
nnoremap <silent>,d :Defx<CR>
autocmd FileType defx call s:defx_my_settings()
function! s:defx_my_settings() abort
  nnoremap <silent><buffer><expr> <CR> defx#do_action('open')
  nnoremap <silent><buffer><expr> c defx#do_action('copy')
  nnoremap <silent><buffer><expr> m defx#do_action('move')
  nnoremap <silent><buffer><expr> p defx#do_action('paste')
  nnoremap <silent><buffer><expr> l defx#do_action('open')
  nnoremap <silent><buffer><expr> E defx#do_action('open', 'vsplit')
  nnoremap <silent><buffer><expr> P defx#do_action('preview')
  nnoremap <silent><buffer><expr> o defx#do_action('open_tree', 'toggle')
  nnoremap <silent><buffer><expr> K defx#do_action('new_directory')
  nnoremap <silent><buffer><expr> N defx#do_action('new_file')
  nnoremap <silent><buffer><expr> M defx#do_action('new_multiple_files')
  nnoremap <silent><buffer><expr> C defx#do_action('toggle_columns', 'mark:indent:icon:filename:type:size:time')
  nnoremap <silent><buffer><expr> S defx#do_action('toggle_sort', 'time')
  nnoremap <silent><buffer><expr> d defx#do_action('remove')
  nnoremap <silent><buffer><expr> r defx#do_action('rename')
  nnoremap <silent><buffer><expr> ! defx#do_action('execute_command')
  nnoremap <silent><buffer><expr> x defx#do_action('execute_system')
  nnoremap <silent><buffer><expr> yy defx#do_action('yank_path')
  nnoremap <silent><buffer><expr> . defx#do_action('toggle_ignored_files')
  nnoremap <silent><buffer><expr> ; defx#do_action('repeat')
  nnoremap <silent><buffer><expr> h defx#do_action('cd', ['..'])
  nnoremap <silent><buffer><expr> ~ defx#do_action('cd')
  nnoremap <silent><buffer><expr> q defx#do_action('quit')
  nnoremap <silent><buffer><expr> <Space> defx#do_action('toggle_select') . 'j'
  nnoremap <silent><buffer><expr> * defx#do_action('toggle_select_all')
  nnoremap <silent><buffer><expr> j line('.') == line('$') ? 'gg' : 'j'
  nnoremap <silent><buffer><expr> k line('.') == 1 ? 'G' : 'k'
  nnoremap <silent><buffer><expr> <C-l> defx#do_action('redraw')
  nnoremap <silent><buffer><expr> <C-g> defx#do_action('print')
  nnoremap <silent><buffer><expr> cd defx#do_action('change_vim_cwd')
endfunction

" PLUGIN: Yggdroot/indentLine
let g:indentLine_color_term = 239

" PLUGIN: junegunn/vim-easy-align
vmap <Enter> <Plug>(EasyAlign)

" PLUGIN: altercation/vim-colors-solarized
set background=dark
colorscheme solarized
