" Note: Skip initialization for vim-tiny or vim-small.
if !1 | finish | endif

if has('vim_starting')
  set nocompatible               " Be iMproved

  " Required:
  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

" Required:
call neobundle#begin(expand('~/.vim/bundle/'))

" Let NeoBundle manage NeoBundle
" Required:
NeoBundleFetch 'Shougo/neobundle.vim'

" My Bundles here:
" Refer to |:NeoBundle-examples|.
" Note: You don't set neobundle setting in .gvimrc!

NeoBundle 'itchyny/lightline.vim'
NeoBundle 'Shougo/neosnippet.vim'
NeoBundle 'Shougo/neosnippet-snippets'
NeoBundle 'scrooloose/nerdtree'
NeoBundle 'altercation/vim-colors-solarized' " Default coloring
NeoBundle 'derekwyatt/vim-scala.git'         " Scala syntax coloring

call neobundle#end()

" Required:
filetype plugin indent on

" If there are uninstalled bundles found on startup,
" this will conveniently prompt you to install them.
NeoBundleCheck

" File Encodings
set encoding=utf-8
set fileencodings=utf-8,cp932,euc-jp

" Behavior
set backspace=indent,eol,start
set nobackup
set writebackup
set history=50
set hlsearch
autocmd BufWritePre * :%s/\s\+$//e " Truncate line-tail space(s)

set autoindent
set smartindent
set expandtab

set tabstop=2
set shiftwidth=2
" Override tab size by detecting file type
augroup filetypedetect
  au BufNewFile,BufRead *.php  setlocal tabstop=4 shiftwidth=4
augroup END

" View
syntax on
set number
set ruler
set wrap
set showcmd
set cursorline
set smartcase
set showmatch
set laststatus=2

" Pulugin Settings
" - NERDTree
nmap <silent> <C-e> :NERDTreeToggle<CR>
vmap <silent> <C-e> <Esc> :NERDTreeToggle<CR>
omap <silent> <C-e> :NERDTreeToggle<CR>
imap <silent> <C-e> <Esc> :NERDTreeToggle<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
let g:NERDTreeShowHidden=1

" Coloring
set background=dark
colorscheme solarized
