#
# zshrc
#

# Import environment specific zshrc
[ -f ~/.zshrc_env ] && source ~/.zshrc_env

# Import common zshrc
[ -f ~/.zshrc_env ] && source ~/.zshrc_common

# Import local zshrc
[ -f ~/.zshrc_local ] && source ~/.zshrc_local

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

