#
# zshrc
#

# Import environment specific zshrc
[ -f ~/.zshrc_env ] && source ~/.zshrc_env

# Import local zshrc
[ -f ~/.zshrc_local ] && source ~/.zshrc_local

# Import common zshrc
[ -f ~/.zshrc_env ] && source ~/.zshrc_common

# Run tmux and exit
tmux && exit
